DROP DATABASE IF EXISTS bigstore_db;
CREATE bigstore_db;

USE bigstore_db;

CREATE TABLE department (
    -- ID INT PRIMARY KEY
    -- NAME VARCHAR(30)
);

CREATE TABLE role (
    -- ID INT PRIMARY KEY
    -- TITLE VARCHAR(30)
    -- SALARY DECIMAL
    -- DEPARTMENT ID
    -- REFERENCE DEPARTMENT TABLE
);

CREATE TABLE employee (
    -- ID INT PRIMARY KEY
    -- FIRST_NAME VARCHAR(30)
    -- LAST_NAME VARCHAR(30)
    -- ROLE_ID INT
    -- REFERENCE ROLE ID
    -- MANAGER_ID INT
    -- REFERENCES OTHER EMPLOYEE THAT IS A MANAGER
    -- NULL IF NOT MANAGED
);
